#!/usr/bin/env python3
"""
Setup Test Data Script

Copies test data from source directories to tests/fixtures/test_data/ for testing purposes.
Supports --skip-r flag to skip R-specific files and --force flag to overwrite existing files.

Usage:
    python tests/scripts/setup_test_data.py [--skip-r] [--force]
"""

import argparse
import shutil
from pathlib import Path


def copy_file(src: Path, dst: Path, force: bool = False) -> bool:
    """Copy a file from src to dst.

    Args:
        src: Source file path
        dst: Destination file path
        force: Overwrite existing file

    Returns:
        True if file was copied, False otherwise
    """
    if dst.exists() and not force:
        print(f"  SKIP: {dst.name} (already exists, use --force to overwrite)")
        return False

    try:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        print(f"  COPIED: {dst.name}")
        return True
    except Exception as e:
        print(f"  ERROR copying {src.name}: {e}")
        return False


def copy_directory(src: Path, dst: Path, force: bool = False) -> int:
    """Copy all files from src directory to dst directory.

    Args:
        src: Source directory path
        dst: Destination directory path
        force: Overwrite existing files

    Returns:
        Number of files copied
    """
    if not src.exists():
        print(f"  ERROR: Source directory does not exist: {src}")
        return 0

    count = 0
    for file in src.iterdir():
        if file.is_file():
            if copy_file(file, dst / file.name, force):
                count += 1
    return count


def create_config_yaml(output_dir: Path) -> bool:
    """Create config.yaml for Python pointing to test_data paths.

    Args:
        output_dir: Directory where config.yaml will be created

    Returns:
        True if config.yaml was created successfully
    """
    config_content = """# OHI Configuration for Testing
# Generated by setup_test_data.py

# Calculation Constants
constants:
  pressures_gamma: 0.5
  resilience_gamma: 0.5
  goal_discount: 1.0
  goal_beta: 0.67
  default_trend: 0
  adjust_trend: 10.0

# Scenario Configuration
scenario_year: 2024

# Paths (relative to project root)
paths:
  # Assessment directory
  assessment_dir: "tests/fixtures/test_data"

  # Configuration files (in conf/ subdirectory)
  conf_dir: "tests/fixtures/test_data/conf"
  goals_csv: "tests/fixtures/test_data/conf/goals.csv"
  pressures_matrix_csv: "tests/fixtures/test_data/conf/pressures_matrix.csv"
  resilience_matrix_csv: "tests/fixtures/test_data/conf/resilience_matrix.csv"
  pressure_categories_csv: "tests/fixtures/test_data/conf/pressure_categories.csv"
  resilience_categories_csv: "tests/fixtures/test_data/conf/resilience_categories.csv"
  scenario_data_years_csv: "tests/fixtures/test_data/conf/scenario_data_years.csv"

  # Data layers
  layers_dir: "tests/fixtures/test_data/layers"
  layers_csv: "tests/fixtures/test_data/layers.csv"

  # Output directory
  output_dir: "tests/fixtures/test_data/comparative"

# Layer Configuration
layer_format: "parquet"

layers:
  id_fields:
    - "rgn_id"
    - "cntry_key"
    - "fao_id"
    - "fao_saup_id"
    - "country_id"
    - "saup_id"
    - "fao_ohi_id"

  region_labels: "rgn_area"
  region_areas: "rgn_area"

# Element Weighting Mappings
element_mappings:
  resilience:
    NP: "np_harvest_tonnes_weigth"
    CP: "cp_habitat_extension"
    LIV: "le_sector_weight"
    ECO: "le_sector_weight"
    HAB: "element_wts_hab_pres_abs"
    LSP: "element_wts_lsp_km2_x_protection"

  pressures:
    NP: "np_harvest_tonnes_weigth"
    CP: "cp_habitat_extension"
    LIV: "le_sector_weight"
    ECO: "le_sector_weight"
    HAB: "element_wts_hab_pres_abs"
    LSP: "element_wts_lsp_km2_x_protection"

# Spatial Configuration
spatial:
  geojson: "tests/fixtures/test_data/eez2015/spatial/rgn_offshore_gcs_mapshaper-simplify_x2_eez-only.geojson"

# Dimension Descriptions
descriptions:
  index: "The overall Index represents the weighted average of all goal scores."

  dimensions:
    score: "This dimension is an average of the current status and likely future."
    status: "This dimension represents the current value of a goal or sub-goal relative to its reference point."
    future: "For this dimension, the likely future is calculated as the projected status in 5 years, informed by the current status, continued trend, inflected upwards by resilience and downwards by pressures."
    trend: "This dimension represents the recent change in the value of the status. Unlike all other dimensions which range in value from 0 to 100, the trend ranges from -1 to 1, representing the steepest declines to increases respectively."
    pressures: "This dimension represents the anthropogenic stressors that negatively affect the ability of a goal to be delivered to people. Pressures can affect either ecological or social (i.e. human) systems."
    resilience: "This dimension represents the social, institutional, and ecological factors that positively affect the ability of a goal to be delivered to people."
"""

    try:
        config_path = output_dir / "config.yaml"
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        print(f"  CREATED: config.yaml")
        return True
    except Exception as e:
        print(f"  ERROR creating config.yaml: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Setup test data by copying source files to tests/fixtures/test_data/"
    )
    parser.add_argument(
        "--skip-r",
        action="store_true",
        help="Skip copying R-specific files (config.R, functions.R)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files",
    )
    args = parser.parse_args()

    # Get the project root directory
    project_root = Path(__file__).parent.parent.parent
    test_data_dir = project_root / "tests" / "fixtures" / "test_data"

    print("=" * 70)
    print("Setup Test Data")
    print("=" * 70)
    print(f"Project root: {project_root}")
    print(f"Test data dir: {test_data_dir}")
    print(f"Skip R files: {args.skip_r}")
    print(f"Force overwrite: {args.force}")
    print("=" * 70)
    print()

    stats = {
        "r_files_copied": 0,
        "conf_files_copied": 0,
        "layer_files_copied": 0,
        "layer_csv_copied": False,
        "config_yaml_created": False,
    }

    # Copy R files if not skipping and chl/ exists
    if not args.skip_r:
        chl_conf_dir = project_root / "chl" / "comunas" / "conf"
        if chl_conf_dir.exists():
            print("Copying R files from chl/comunas/conf/...")
            # Copy config.R
            if (chl_conf_dir / "config.R").exists():
                if copy_file(
                    chl_conf_dir / "config.R", test_data_dir / "conf" / "config.R", args.force
                ):
                    stats["r_files_copied"] += 1
            # Copy functions.R
            if (chl_conf_dir / "functions.R").exists():
                if copy_file(
                    chl_conf_dir / "functions.R", test_data_dir / "conf" / "functions.R", args.force
                ):
                    stats["r_files_copied"] += 1
        else:
            print("  WARNING: chl/comunas/conf/ does not exist, skipping R files")

    # Copy config files from data/conf/
    conf_src_dir = project_root / "data" / "conf"
    conf_dst_dir = test_data_dir / "conf"
    if conf_src_dir.exists():
        print("\nCopying configuration files from data/conf/...")
        stats["conf_files_copied"] = copy_directory(conf_src_dir, conf_dst_dir, args.force)
    else:
        print("  ERROR: data/conf/ does not exist")
        return 1

    # Copy layer files from data/layers/csv/
    layers_src_dir = project_root / "data" / "layers" / "csv"
    layers_dst_dir = test_data_dir / "layers"
    if layers_src_dir.exists():
        print("\nCopying layer files from data/layers/csv/...")
        stats["layer_files_copied"] = copy_directory(layers_src_dir, layers_dst_dir, args.force)
    else:
        print("  ERROR: data/layers/csv/ does not exist")
        return 1

    # Copy layers.csv
    layers_csv_src = project_root / "data" / "layers.csv"
    layers_csv_dst = test_data_dir / "layers.csv"
    if layers_csv_src.exists():
        print("\nCopying layers.csv...")
        if copy_file(layers_csv_src, layers_csv_dst, args.force):
            stats["layer_csv_copied"] = True
    else:
        print("  ERROR: data/layers.csv does not exist")
        return 1

    # Create config.yaml
    print("\nCreating config.yaml for Python...")
    if create_config_yaml(test_data_dir):
        stats["config_yaml_created"] = True

    # Print summary
    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)
    print(f"R files copied: {stats['r_files_copied']}")
    print(f"Config files copied: {stats['conf_files_copied']}")
    print(f"Layer files copied: {stats['layer_files_copied']}")
    print(f"Layers.csv copied: {stats['layer_csv_copied']}")
    print(f"Config.yaml created: {stats['config_yaml_created']}")
    print("=" * 70)

    # Exit with success
    return 0


if __name__ == "__main__":
    exit(main())
